# Generated by Django 4.0.4 on 2022-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_options_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification',
            field=models.CharField(max_length=10),
        ),
    ]
