from enum import Enum


class Emoji (Enum):
    football = '⚽'
    heart = '❤️'
    explosion = '💥'
    bomb = '💣'
    rocket = '🚀'
    fire = '🔥'
    commet = '☄️'
    lightning = '⚡'
    danger = '⚠️'
    stop = '🚫'
    calendar = '🗓'
    marker = '📍'
    clock = '🕖'
    people = '👥'
    money = '💰'
    pencil = '✏️'
    credit_card = '💳'
    orange = '🟧'
    blue = '🟦'
    green = '🟩'
    running_guy = '🏃‍♂️'
